openapi: 3.0.0
info:
  title: Payment Processing Microservice
  version: 1.0.0
  description: A microservice to simulate payment creation, retrieval, and status update.

servers:
  - url: http://localhost:3000/api

paths:
  /payments:
    post:
      summary: Create a payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                currency:
                  type: string
              required:
                - amount
                - currency
      responses:
        "201":
          description: Payment created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"

    get:
      summary: Get all payments
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of results per page
        - in: query
          name: status
          schema:
            type: string
            enum: [pending, completed, failed]
          description: Filter payments by status
      responses:
        "200":
          description: List of payments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Payment"

  /payments/{id}:
    get:
      summary: Get a payment by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Payment details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        "404":
          description: Payment not found

    patch:
      summary: Update payment status
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, completed, failed]
              required:
                - status
      responses:
        "200":
          description: Updated payment
        "404":
          description: Payment not found

components:
  schemas:
    Payment:
      type: object
      properties:
        id:
          type: string
        amount:
          type: number
        currency:
          type: string
        status:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
